### PR TITLE
Previously, the spec for block level tokens was causing confusion and…

### PR DESCRIPTION
**Pull request by windwardrail**
… implementation problems. This commit updates the spec to require specifying block level tokens on their own line. It also removes the special handling of comment blocks. The functionality to provide useful content prompts will likely be implemented in the future in the form of WIP annotations.

### CODE REVIEW

**Comment by shnewto** [comment]
@windwardrail Any chance an acceptance criteria for a change to the spec is that this repo's `README.md` fills its `README.rx`? It'd help convince me that the changes work as expected and that a user can still refer to the examples for their own applications.

**Comment by shnewto** [comment]
In the current state `howser` reports `Rx Rejected!`

**Comment by windwardrail** [comment]
Yes, I do need to update the README.rx.

**Comment by windwardrail** [comment]
Closing until the prescription for the readme is updated and can be validated in Howser

**Pull request closed without merging**
